In [2]:
import numpy as np
import pandas as pd

In [3]:
#Number 1
zeros = np.zeros((10,10))
zeros=zeros.astype(np.int64)
zeros[0]=1
zeros[9]=1
zeros[:,0]=1
zeros[:,9]=1
zeros


array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]], dtype=int64)

In [19]:
#Number 2
zeros = np.zeros((10,10))
zeros[1::2,::2] = 1
zeros[::2,1::2] = 1
zeros

array([[0., 1., 0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0., 1., 0.]])

In [119]:
#Number 3
#return only positive numbers
randomData = np.random.randn(3,3,3)
print(randomData)

x=randomData[(randomData > 0)]

x

[[[-0.01846485 -0.27545685 -0.93290847]
  [ 0.8822582   0.70055279  0.4972205 ]
  [ 2.00726107  0.00909301 -1.12455495]]

 [[ 0.55349821  0.9305139  -0.30296216]
  [ 1.40202054  1.36225921  0.08757673]
  [ 0.77363422 -2.13444724  1.16476292]]

 [[-2.17104493 -0.36952203  0.98659664]
  [ 0.08771026 -0.54099972  1.37367724]
  [-1.95295603 -0.77573744  0.85002391]]]


array([0.8822582 , 0.70055279, 0.4972205 , 2.00726107, 0.00909301,
       0.55349821, 0.9305139 , 1.40202054, 1.36225921, 0.08757673,
       0.77363422, 1.16476292, 0.98659664, 0.08771026, 1.37367724,
       0.85002391])

In [47]:
#Number 4
x = np.random.randn(10,10)
# print(x)
xmax=x.max()
xmin=x.min()
xrange=xmax-xmin
print("Max:",xmax,",Min:",xmin,",Range:",xrange)


Max: 2.6746679256444614 ,Min: -2.6044712034354167 ,Range: 5.279139129079878


In [21]:
#Number 5
x = np.ones((12,12))
# print(x)
x = x.astype(np.int64)
for i in range(0,12):
    for j in range(0,12):
        x[i,j] = x[i,j]*(i + 1)*(j + 1)
x

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12],
       [  2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24],
       [  3,   6,   9,  12,  15,  18,  21,  24,  27,  30,  33,  36],
       [  4,   8,  12,  16,  20,  24,  28,  32,  36,  40,  44,  48],
       [  5,  10,  15,  20,  25,  30,  35,  40,  45,  50,  55,  60],
       [  6,  12,  18,  24,  30,  36,  42,  48,  54,  60,  66,  72],
       [  7,  14,  21,  28,  35,  42,  49,  56,  63,  70,  77,  84],
       [  8,  16,  24,  32,  40,  48,  56,  64,  72,  80,  88,  96],
       [  9,  18,  27,  36,  45,  54,  63,  72,  81,  90,  99, 108],
       [ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100, 110, 120],
       [ 11,  22,  33,  44,  55,  66,  77,  88,  99, 110, 121, 132],
       [ 12,  24,  36,  48,  60,  72,  84,  96, 108, 120, 132, 144]],
      dtype=int64)

In [25]:
#Number 6
recipe = pd.Series(['1 package','1 cup' ,'1 tablespoon','1/2 teaspoon', '1 teaspoon', '1 teaspoon','1/2 teaspoon',' 1/8 teaspoon',
                    '3', '15 ounce can','1 1/4 cup'], 
                 index=['store-bought pie-crust','light brown sugar','all-purpose flour','salt','ground cinnamon',
                    'ground ginger','ground nutmeg','ground cloves','large eggs','pumpkin puree','evaporated milk'])

recipe

store-bought pie-crust        1 package
light brown sugar                 1 cup
all-purpose flour          1 tablespoon
salt                       1/2 teaspoon
ground cinnamon              1 teaspoon
ground ginger                1 teaspoon
ground nutmeg              1/2 teaspoon
ground cloves              1/8 teaspoon
large eggs                            3
pumpkin puree              15 ounce can
evaporated milk               1 1/4 cup
dtype: object

In [30]:
#Number 7
for i in range(len(recipe.index)):
    x=recipe.sort_index()
    print(x.index[i].capitalize())

All-purpose flour
Evaporated milk
Ground cinnamon
Ground cloves
Ground ginger
Ground nutmeg
Large eggs
Light brown sugar
Pumpkin puree
Salt
Store-bought pie-crust


In [46]:
#Number 8
#Get index from question 6
recipe_prices = pd.Series([5,1 ,3.5,.99, 1.99,1.99,1.99,1.99,2.99, 3.99,1.29], index=recipe.index)

print(recipe_prices)
print("Total price:         ",recipe_prices.sum())
print("Average price:       ", recipe_prices.mean())
print("Most expensive item: ",recipe_prices.idxmax(),recipe.max())
print("Least expensive item:",recipe_prices.idxmin(),recipe.min())


store-bought pie-crust    5.00
light brown sugar         1.00
all-purpose flour         3.50
salt                      0.99
ground cinnamon           1.99
ground ginger             1.99
ground nutmeg             1.99
ground cloves             1.99
large eggs                2.99
pumpkin puree             3.99
evaporated milk           1.29
dtype: float64
Total price:          26.72
Average price:        2.429090909090909
Most expensive item:  store-bought pie-crust 3
Least expensive item: salt  1/8 teaspoon


In [36]:
#Number 9
recipe_prices*.8

store-bought pie-crust    4.000
light brown sugar         0.800
all-purpose flour         2.800
salt                      0.792
ground cinnamon           1.592
ground ginger             1.592
ground nutmeg             1.592
ground cloves             1.592
large eggs                2.392
pumpkin puree             3.192
evaporated milk           1.032
dtype: float64

In [38]:
#Number 10
data = {'ingredients':['store-bought pie-crust','light brown sugar','all-purpose flour','salt','ground cinnamon',
                    'ground ginger','ground nutmeg','ground cloves','large eggs','pumpkin puree','evaporated milk'],
       'price':[5,1 ,3.5,.99, 1.99, 1.99,1.99,1.99,2.99, 3.99,1.29]}
df_recipe = pd.DataFrame(data, columns=['ingredients','price','quantity'], index=range(1,len(data['ingredients'])+1))
df_recipe

ingredients  price quantity
1   store-bought pie-crust   5.00      NaN
2        light brown sugar   1.00      NaN
3        all-purpose flour   3.50      NaN
4                     salt   0.99      NaN
5          ground cinnamon   1.99      NaN
6            ground ginger   1.99      NaN
7            ground nutmeg   1.99      NaN
8            ground cloves   1.99      NaN
9               large eggs   2.99      NaN
10           pumpkin puree   3.99      NaN
11         evaporated milk   1.29      NaN

In [39]:
#Number 11
df_recipe.loc[[3,5,10],'quantity'] = 5
df_recipe.loc[[9,2,6],'quantity'] = 2
df_recipe.loc[[11,8,7],'quantity'] = 3
df_recipe.loc[[4,1],'quantity'] = 4
df_recipe

ingredients  price quantity
1   store-bought pie-crust   5.00        4
2        light brown sugar   1.00        2
3        all-purpose flour   3.50        5
4                     salt   0.99        4
5          ground cinnamon   1.99        5
6            ground ginger   1.99        2
7            ground nutmeg   1.99        3
8            ground cloves   1.99        3
9               large eggs   2.99        2
10           pumpkin puree   3.99        5
11         evaporated milk   1.29        3

In [40]:
#Number 12
df_recipe['Total Price']=df_recipe['price']*df_recipe['quantity']
df_recipe

ingredients  price quantity Total Price
1   store-bought pie-crust   5.00        4        20.0
2        light brown sugar   1.00        2         2.0
3        all-purpose flour   3.50        5        17.5
4                     salt   0.99        4        3.96
5          ground cinnamon   1.99        5        9.95
6            ground ginger   1.99        2        3.98
7            ground nutmeg   1.99        3        5.97
8            ground cloves   1.99        3        5.97
9               large eggs   2.99        2        5.98
10           pumpkin puree   3.99        5       19.95
11         evaporated milk   1.29        3        3.87

In [44]:
#Number 13
#open write method to create text file, not pandas
# df_recipe.to_csv('pumpkin-pie-file.txt')
recipe_file = open('pumpkin-pie-file.txt', 'w')
recipe_file.write(df_recipe.to_string())
recipe_file.close()

In [45]:
#number 14
df_recipe.to_csv('pumpkin-pie-file.csv')